port: /dev/ttyDXL_puppet_left


groups:
  arm:
    torque_enable: false

singles:
  gripper:
    torque_enable: false




# groups:
#   arm:
#     operating_mode: position
#     profile_type: velocity
#     profile_velocity: 0
#     profile_acceleration: 0
#     torque_enable: true

# singles:
#   gripper:
#     operating_mode: linear_position
#     profile_type: velocity
#     profile_velocity: 0
#     profile_acceleration: 0
#     torque_enable: true
