port: /dev/ttyDXL_puppet_left


groups:
  arm:
    operating_mode: position
    profile_type: time
    profile_velocity: 5000
    profile_acceleration: 300
    torque_enable: false

singles:
  gripper:
    operating_mode: pwm
    torque_enable: false